export interface Widget {
  id: string;
  title: string;
  description: string;
  type: 'price_chart' | 'financial_table' | 'news_sentiment' | 'macro_indicators' | 'crypto_chart' | 'ai_artifact' | 'text_note';
  category: 'Equity' | 'Economy' | 'Crypto' | 'General' | 'AI';
  isLinked: boolean;
  customContent?: string; // For text notes or specific AI text/table HTML
  customData?: any; // Custom data structure for charts generated by AI
}

export interface DashboardApp {
  id: string;
  name: string;
  description: string;
  icon: string; // Name of Lucide icon
  defaultTicker: string;
  defaultDateRange: string;
  widgets: Widget[];
  suggestedPrompts: string[];
  systemInstruction: string;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  timestamp: string;
  artifact?: {
    title: string;
    type: Widget['type'];
    data: any;
    content?: string;
  };
}

export interface GlobalParams {
  ticker: string;
  dateRange: string;
}
